### ISSUE TITLE
force diagram

### ISSUE THREAD

**Issue by Bob20061225** [Daanunder/TSHD_production_estimation#6]
Could you please provide a force diagram for the cutting force, and explanation of the visor parameters ?

**Comment by Daanunder** [comment]
This is not how issues work. If there is missing something in the code, let me know. If you suggest an improvement, add a pull request. 

But if you just want to understand, there's a background file if you're explaining parameters of the cutting force and visor parameters, also the source Miedema (2019) has more details on calculating such a force. 

https://github.com/Daanunder/TSHD_production_estimation/blob/f6204a9109c82bab55e72d9469810729a406d4d1/Background.ipynb

**Comment by Bob20061225** [comment]
Dear Daanynder,


Thank you for the reply.


Why don't you make the blade angle dependent on visor angle?


Best Regards.


Bob Liu
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/21/2024 19:14 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [Daanunder/TSHD_production_estimation] force diagram (Issue #6) |

This is not how issues work. If there is missing something in the code, let me know. If you suggest an improvement, add a pull request.

But if you just want to understand, there's a background file if you're explaining parameters of the cutting force and visor parameters, also the source Miedema (2019) has more details on calculating such a force.

https://github.com/Daanunder/TSHD_production_estimation/blob/f6204a9109c82bab55e72d9469810729a406d4d1/Background.ipynb

**Comment by Daanunder** [comment]
If you require the visor- and blade angle to be dependent, please make it
so.

Its not illogical, I just did not do it. It is also listed as an
improvement at the top of main.py.

If you implement it, I suggest to keep a variable 'initial blade angle' or
something, then you can create a Merge Request and I can have a look.
